<div id="are-filters">
  <form method="GET" action="">
  <?php $dataFilterLinkHtml = '<li><input type="hidden" name="" class="mare-value"><span class="filter-link"></span><button type="button" class="o-icon-close clear-filter" aria-label="Clear filter"></button></li>'; ?>
  <div id="selected-filters" class="empty" data-filter-link-template='<?php echo $dataFilterLinkHtml; ?>' >
    <h4>Selected filters</h4>
    <div class="denominations empty" data-resource-type="mare:denomination">
      <h5>Denominations</h5>
      <ul class="filters"></ul>
    </div>
    <div class="counties empty" data-resource-type="mare:county">
      <h5>Counties</h5>
      <ul class="filters"></ul>
    </div>
  </div>
  <?php 
    echo $this->partial('common/are-filter-select', [
        'heading' => 'Template',
        'filterResourceType' => 'template',
        'filterResources' => [],
        'resourceTemplateId' => '',
        'template' => true,
    ]);

    echo $this->partial('common/are-filter-select', [
        'heading' => 'Denomination family',
        'filterResourceType' => 'mare:denominationFamily',
        'filterResources' => $denominationFamilies,
        'resourceTemplateId' => $resourceTemplateIds['Denomination']
    ]);


    echo $this->partial('common/are-filter-select', [
        'heading' => 'State/Territory',
        'filterResourceType' => 'mare:stateTerritory',
        'filterResources' => $stateTerritories,
        'resourceTemplateId' => $resourceTemplateIds['County']
    ]);
  ?>
  <button type="submit" class="filter-submit button">Apply filters</button>

  <div class="query-display">
  <span class="filter-data" data-resource-type="mare:denomination" data-parent-resource-type="mare:denominationFamily" data-parent-property-id="<?php echo $denominationFamilyPropertyId; ?>" data-active-ids="<?php echo (isset($areCurrentFilters['mare_denomination'])) ? implode(",", $areCurrentFilters['mare_denomination']) : ''; ?>"></span>
  <span class="filter-data" data-resource-type="mare:county" data-parent-resource-type="mare:stateTerritory" data-parent-property-id="<?php echo $stateTerritoriesPropertyId; ?>"  data-active-ids="<?php echo (isset($areCurrentFilters['mare_county'])) ? implode(",", $areCurrentFilters['mare_county']) : ''; ?>"></span>
  </div>
  </form>
</div>
